# -*- coding: utf-8 -*-
"""28/04/23 LOOP AND RANGE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACxl261mKoVkYNB5pgBq-sdNdpBlQM27
"""

a=1
print(a)
a=a+1
print(a)
a=a+1
print(a)
a=a+1
print(a)
a=a+1
print(a)
a=a+1
print(a)

for a in range(5):
  print(a)

for f in range(5):
  print(a)

a=1
for f in range(5):
  print(a)
  a=a+1

a=3*1
for a in range(3,32, 3):
  print(a)
  a=a+3

num = 3

# To take input from the user
# num = int(input("Display multiplication table of? "))

# Iterate 10 times from i = 1 to 10
for i in range(1, 11):
   print(num, 'x', i, '=', num*i)

number = int(input ("Enter the number: "))
print ("The Multiplication Table of:", number)
for count in range(3,11):
   print (number, 'x', count, '=', number * count)

t = int(input ("Enter the number: "))
for f in range(1,11):
  print(t, "x", f, "=" ,f*t)

for t in range(1, 21, 2):
    print("table of", t)
    for f in range(1, 11):
        print(t, "x", f, "=", f*t)
    print()

for i in
t=int(input("enter the number:"))
for f in range(1,11):
  print(t, "x", f, "=" ,f*t)