# -*- coding: utf-8 -*-
"""assignment no 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGsxqt_5htJEEKT1GDTLUjYXTLcRHkSg
"""

NAMES= [('ALI', 35),('AHMAD', 25),('SAIM', 30)]
x = min(NAMES)
print(x)

A=98
B=45
C=32
x = max(A,B,C)
print(x)

a = 'hello world.'
print(a.capitalize())

introduction = 'My name is umer and currently i am studing in umt.'
print(introduction.title())

name = [ "Anie" , "Bob" , "Cavin" , "David" ]
print(name[1])
for x in name;
 print(x)

print(name[1])
for x in name:
 print(x)

print(len(name))

No=43
Name="M.UMER"
Address= "23 Multan road ,Lahore"
print(No)
print("Name, Address")

print(Name.upper())
print(Name.lower())

print(Name.isalnum())

print(Name.isalpha())

print(Name.islower())

print(Name.isnumeric())

print(Name.isspace())

print(Name.istitle())

name = 'Cathy'
country = 'UK'

print(f'{name} is from {country}')

str1 = "Hello, world!"
str2 = "I love Python."
str3 = "Hello, world!"
print(str1 == str2)
print(str1 == str3)

s1= 'HELLO HUNTER'
s2= s1[6:12]
print(s1)

greeting = 'Hello'
for letter in greeting:
    print(letter)

name = "Python"
print(name)

message = "I love Python."
print(message)

message = """
it is to inform you that the
current program shows the syntax error
"""
print(message)

greet = 'Hello'
print(len(greet))

greet = "Hello, "
name = "Jack"
result = greet + name
print(result)

CREATELIST = ["UMER", "ABDULLAH", "AMMAR"]
print(CREATELIST)

x = "This is "
y = "Python"
z = x + y + '.'
print(z)