# -*- coding: utf-8 -*-
"""ASSIGNMENT NO 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yaMuazgHP4AC27VECEZcwlaRqCKw9thv
"""

print("Enter Your English Number")
english = float(input())
print("Enter Your Chemistry Number")
chemistry = float(input())
print("Enter Your Math Number")
math = float(input())
print("Enter Your Physics Number")
physics =float(input())
print("Enter Your Computer Number")
computer =float(input())

print("Total Gaining Number")

total = english + chemistry + math + physics + computer
print(total)

print ("Percentage")
percentage = (total/500) * 100
print ("Remarks")

if percentage<=33:
  print("fail")
  print("try again")
if percentage>=33:
  print("pass")
  print("congratulations")