# -*- coding: utf-8 -*-
"""Assignment 2&3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lHp0rgV80Dm_cclZEn81kYF1aHAzVte6
"""

for t in range(1, 23, 2):
  print("TABLE OF ODD NO")
  print("table of", t)
  for f in range(1, 11):
        print(t, "x", f, "=", f*t)
  print()

for t in range(1,6):
    for f in range(1,t+1):
         print(f,end="")
    print()

for line in range(5,0,-1):
    for f in range(line):
        print("*",end="")
    print()

n = 4
print()
for f in range(1, n+1):
    for a in range(1, n-f+1):
        print(" ", end="")
    for a in range(1, f+1):
        print(a, end="")
    for a in range(f-1, 0, -1):
        print(a, end="")
    print()

for f in range(n-1, 0, -1):
    for a in range(1, n-f+1):
        print(" ", end="")
    for a in range(1, f+1):
        print(a, end="")
    for a in range(f-1, 0, -1):
        print(a, end="")
    print()