# -*- coding: utf-8 -*-
"""Class box.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBl8LVuUvXD8OEe0n9lBfDJ2KNtyYIi0
"""

class box:
  def area(self):
      print("Area is ",self.width*self.height)
  def __init__(self, width, height):
    self.width=width
    self.height=height

b=box(5, 6)
b2=box(3, 8)
b3=box(5, 9)

b.area()
b2.area()
b3.area()