# -*- coding: utf-8 -*-
"""FILE 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WURWiZJVnecNSMJZfRWiBu0Y1caQ8jJJ
"""

print("welcome..")
print("Muhammad Umer Faheem")

Price =456.56
print (Price)
print (type(Price))

print("Enter Your English Number")
english = float(input())
print("Enter Your Chemistry Number")
chemistry = float(input())
print("Enter Your Math Number")
math = float(input())
print("Enter Your Physics Number")
physics =float(input())
print("Enter Your Computer Number")
computer =float(input())

print("Total Gaining Number")

total = english + chemistry + math + physics + computer
print(total)

print ("Percentage")
percentage = (total/500) * 100
print ("Remarks")

if percentage<=33:
  print("fail")
  print("try again")
if percentage>=33:
  print("pass")
  print("congratulations")



a = 10
b = 30
c = 45
d = 55
sum = a+b+c+d
if sum>100:
 print("large values")
else:
 print("small values")

total_marks =int(input("Enter marks"))
print(total_marks)

if total_marks < 86:
 print("fail")

if total_marks > 90:
 print("pass")

a = 123
b = 123
a = b = 1/2
print (a , b)

a= 54
b = 64
c=a/b
print(c)

a = int(input("Enter First Number"))
b = int(input("Enter Second Number"))
op = input("Enter Operator")
if op == "*":
 ans = a*b
else:
 ans=a+b
print(ans)

a = int(input("ENTER YOUR 1st NO"))
b = int(input("ENTER YOUR 2nd NO"))
c = int(input("ENTER YOUR 3rd NO"))
d = int(input("ENTER YOUR 4th NO"))
e = int(input("ENTER YOUR 5th NO"))
f = int(input("ENTER YOUR 6th NO"))
op = input("ENTER OPERATOR")
if op=="*,+,-,/":
  ans = a*b*c*d*e*f
else:
      ans = a+b+c+d+e+f
      print(ans)

qw = int(input("enter no"))
qu = int(input("enter no"))
op = input("enter operator")
if op=="*":
  ans = qw*qu
else:
    ans =qw+qu
    print(ans)

a = int(input("enter your no "))
b = int(input("enter your no "))
op = input("enter operator")
if op=="*":
  ans = a*b
else:
    ans = a+b
    print(ans)

k= [2,4,6,8,10]
print(k)

k = [2,4,6,8,9,2,4]
print("while loop")
i=0
while i < len(k):
  print(k[i])
  i=i+1
print("for loop")
for i in k:
  print(i)

print(len(k))

print("Maximum ", max(k))
print("Minimum ", min(k))
print("Sum" , sum(k))
print("Average", sum(k)/len(k))

