# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103Qj1BfYPExrQkebY6K7vTo8I3RJW2Sp
"""

print("welcome")
print("welcome")
print("welcome")
print("welcome")
print("welcome")
print("welcome")
print("welcome")
print("welcome")

def wel(name):
  print("welcome..", name)

wel("ALI")
wel("ZAHEEB")
wel("ABDULLAH")
wel("AHMAD")
wel("ZAIN")

def area(width,height):
  ans=width*height
  print("Area is ", ans)

area(7,1)
area(6,2)
area(5,3)
area(4,5)
area(3,7)

def min2hours(mins):
  return mins/60

totalhours=min2hours(70)+min2hours(50)+min2hours(20)
print("totalhours",totalhours)

import datetime
a = datetime.datetime.now()
y = int(input("ENTER YEAR: "))
m = int(input("ENTER MONTH: "))
d = int(input("ENTER DAY: "))
b = datetime.datetime(y, m, d)
print(a. year)
print(a. month)
print(a. day)
print(b. year)
print(b. month)
print(b. day)

print(b.strftime("%Y/%m/%d/%y"))