# -*- coding: utf-8 -*-
"""Nested loops lectures (while loop)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYDEhf2-fwWTMjG-MG_BkdTyvvPxdX2_
"""

for line in range(1,6):
 stars= ""
 for star in range(1,6):
  stars = stars+ "*"
 print(stars)

for line in range(1,6):
 stars= ""
 for star in range(1,line+1):
  stars = stars+ "*"
 print(stars)

for line in range(-6,0,1):
  stars= ""
  for star in range(-6,line+1):
   stars = stars+ "*"
  print(stars)

for n in range(2,12,2):
  for n in range(1,6):
    print(n,end="")

  print()

for n in range(2,12,2):
  for n in range(n,n+10,2):
    print(n,end="")

  print()

a=1
while (a<=10):
  if (a!=5):
    print(a)
    print(a+1)
    print(a+2)
    print(a+3)
    print("...")
    a=a+1

a=1
while (a<=10):
  if (a==5):
    a=a+1
    continue;
  print(a)
  print(a+1)
  print(a+2)
  print(a+3)
  print("...")
  a=a+1

a=1
while (a<=10):
  if (a==5):
    a=a+1
    break;
  print(a)
  print(a+1)
  print(a+2)
  print(a+3)
  print("...")
  a=a+1

a=1
while(1):
  print(a)
  a=a+1

a=1
sum=0
while(1):
  a = int(input("enter number , except 0"))
  print("your score is",a)
  sum=sum+a
  if (a==0):
      break

print("your score is", sum)