# -*- coding: utf-8 -*-
"""project no 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8mJRvqdWKEw9SEXsqnYLG_SvLmyuYLA
"""

import random

secret_number = random.randint(1, 50)

print("Welcome to Guess the Number!")
print("I'm thinking of a number between 1 and 50.")
print("Can you guess it?")

while True:
    try:
        guess = int(input("Enter your guess: "))
    except ValueError:
        print("Please enter a number")
        continue

    if guess < secret_number:
        print("Too low! Try again.")
    elif guess > secret_number:
        print("Too high! Try again.")
    else:
        print("Congratulations! You guessed the number")
        break