# -*- coding: utf-8 -*-
"""String_Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJvh212zR79FZLQAZHFLgtwYgBvnVekz
"""

a=76
sname="Ali"
address= "23 Multan road ,Lahore"
Grade = 'B+'

print(a)
print("sname, address")

print(sname[1])
for x in sname:
 print(x)

print(len(sname))

print(len(address))

print(sname.upper())
print(sname.lower())

print(address)

print(address.replace('k','d'))

print(address.replace('o','e'))

print(address.replace('Lahore','Karachi'))

address = (address.replace('Lahore','Karachi'))
print(address)

grades = [ "A" , "B" , "C" , "D" ]
print(grades[2])
for x in grades:
 print(x)

x1= 'english'
x2= 'chemistry'
x3= 'math'
x4= 'pf'
for x in grades:
 if x == "x1":
  print(x, "Excellent")
 elif x == "x2":
  print(x, "Good")
 elif x == "x3":
  print(x, "Hardworking")
 elif x == "x4":
  print(x, "Work more and more")
 else:
  print(x,"much effort required")

x = ("chemistry , math , english")
x= (input("Please enter a letter grade: "))
if grade >= A:
    grade == "4.0"
elif grade < A:
      grade < "4.0"
print(grade)

a = [' Umer.a']
a.append('zaheeb')