# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7A7i4i6ZWxxRNI1k1QKxfz_gD1ZMSVB
"""

row=2
while row<=10:
  coulumn = row
  while coulumn <= row + 8:
     Print(coulumn, end ="")
       column += 2:
  print()
  row+=2

for a in range (3):
 for num in range(1, 5):
  print(num,end=" "())
 print()