# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10RgW-x4tQ3eW9MVU9UF6nI7StKZV3hzl
"""

a = ['umer' , 'ahmad' ,'ali']
a.pop(1)

chemistry =int(input("Enter marks: "))
math =int(input("Enter marks: "))
english =int(input("Enter marks: "))
PF=int(input("Enter marks: "))
avg=(chemistry+math+english+PF)/4
if(avg>=90):
    print("Grade: A")
elif(avg>=80 , avg<90):
    print("Grade: B")
elif(avg>=70 , avg<80):
    print("Grade: C")
elif(avg>=60 , avg<70):
    print("Grade: D")
else:
    print("Grade: F")